{
 "title": "Todo List Web App Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  increase(todoapp_requests_total[$__range])\r\n  * on(pod) group_left()\r\n  kube_pod_status_phase{phase=\"Running\", namespace=\"todo-app\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n          1 -\r\n          (\r\n            sum(rate(todoapp_requests_total{namespace=\"todo-app\", job=\"todoapp-service\", exported_endpoint=~\"simulate_.*\"}[$__range]))\r\n            /\r\n            sum(rate(todoapp_requests_total{namespace=\"todo-app\", job=\"todoapp-service\"}[$__range]))\r\n          )\r\n        )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate by Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (\r\n  rate(todoapp_requests_total[$__range])\r\n  * on(pod) group_left()\r\n  kube_pod_status_phase{phase=\"Running\", namespace=\"todo-app\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (pod) (\r\n    rate(todoapp_requests_total{exported_endpoint=~\"simulate_.*\"}[$__range])\r\n    * on(pod) group_left()\r\n    kube_pod_status_phase{phase=\"Running\", namespace=\"todo-app\"}\r\n  )\r\n)\r\n/\r\n(\r\n  sum by (pod) (\r\n    rate(todoapp_requests_total[5m])\r\n    * on(pod) group_left()\r\n    kube_pod_status_phase{phase=\"Running\", namespace=\"todo-app\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(todoapp_request_duration_seconds_bucket[$__range])\r\n    * on(pod) group_left()\r\n    kube_pod_status_phase{phase=\"Running\", namespace=\"todo-app\"}\r\n  )\r\n)",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Latency Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (le) (\r\n  rate(todoapp_request_duration_seconds_bucket[$__range])\r\n  * on(pod) group_left()\r\n  kube_pod_status_phase{phase=\"Running\", namespace=\"todo-app\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}